services:
  config-server:
    build:
      pulse-monitoring-config-server
    mem_limit: 200m
    mem_reservation: 50m

  redis:
    image: redis

  pulse-analyser:
    build:
     pulse-analyser
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      - KAFKA_PASSWORD=******
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis

  average-populator:
    build:
      pulse-monitoring-average-populator
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_PASSWORD=******
      - KAFKA_PASSWORD=******

  average-reducer:
    build:
      pulse-monitoring-avg-reducer
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_PASSWORD=******
      - REDIS_HOST=redis

  doctor-data-provider:
    container_name: doctor-data-provider
    build:
      pulse-monitoring-doctor-data-provider
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_PASSWORD=******
      - POSTGRES_USERNAME=******
      - POSTGRES_DATABASE=******
      - POSTGRES_HOST=******

  pulse-monitoring-gateway:
    container_name: pulse-monitoring-gateway
    build:
      pulse-monitoring-gateway
    ports:
      - "9090:9090"
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      - DATA_PROVIDER_URL=http://doctor-data-provider:8080
      - VISITS_HOST=back-office-visits
      - SENSORS_HOST=back-office-sensors

  jumps-notifier:
    container_name: jumps-notifier
    build:
      pulse-monitoring-jumps-notifier
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_PASSWORD=******
      - USER_NAME=******
      - MAIL_PASSWORD=******
      - DATA_PROVIDER_URL=http://doctor-data-provider:8080

  jumps-populator:
    container_name: jumps-populator
    build:
      pulse-monitoring-jumps-populator
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_PASSWORD=******
      - KAFKA_PASSWORD=******

  back-office-sensors:
    build:
      pulse-monitoring-sensor-values-back-office
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      - MONGO_PASSWORD=******

  back-office-visits:
    build:
      pulse-monitoring-visits-back-office
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      - POSTGRES_PASSWORD=******
      - POSTGRES_USERNAME=******
      - POSTGRES_DATABASE=******
      - POSTGRES_HOST=******
