spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: xmtfeqbeixxfrj
    url: jdbc:postgresql://ec2-35-168-194-15.compute-1.amazonaws.com:5432/d2j8456pl1o4ss
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect